
version: '3.3'
services:

  golang:
    pid: host
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
      
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      volumes:
       -postgres:/data/postgres
      ports:
        -"5432:5432"
volumes:
  postgres:
    driver: local
